apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  labels:
    name: todoapp
    app: web
spec:
  containers:
  - name: todoapp
    image: jaspreet911/jastodo:1.3
    ports:
      - containerPort: 8080
    env:
      - name: ASPNETCORE_URLS
        value: http://+:8080
      - name: WebApiBaseAddress
        value: http://webapi
